### ISSUE TITLE
Provide prebuild binaries on releases

### ISSUE THREAD

**Issue by viceice** [marwan-at-work/mod#19]
We use this tool at [renovate](https://github.com/renovatebot/renovate) as post upgrade step.
We like to download the tool as prebuild binary instead of compiling it on the fly to safe resources.

Currently we only need `linux_amd64` but we'll need `linux_arm64` soon.

//cc @rarkins

**Comment by marwan-at-work** [comment]
Hi there 👋🏼 

Just FYI, even if there was a pre-compiled binary, your host machine still needs the `go` command installed because all Go static analysis tools (including this one) are expected to use `x/go/packages` which shells out to `go list`. 

But in either case, having precompiled release binaries sounds nice and I'm happy to accept a PR that uses GitHub Actions, otherwise I'll find some free time in the future to do so :) 

Thank you!

**Comment by viceice** [comment]
@marwan-at-work Yes, go will be installed. Can you please create a release, so we can use the new binaries?
