### ISSUE TITLE
Does not require import paths on build tag'd files

### ISSUE THREAD

**Issue by djui** [marwan-at-work/mod#7]
If a file (e.g. `foo_test.go`) includes `//+build integration`, it won't touch it to rewrite it.

**Comment by marwan-at-work** [comment]
@djui thanks for bringing this up. 

I added a new flag so you can do `mod upgrade -buildflags=-tags=integration` 

This is because the go compiler has no option to parse *all* go files so we have to be explicit about the build tags.

I'll think about whether it's worth replacing `go/packages` with manual parsing of go files so that we avoid having to explicitly pass `-buildflags`
